Rver 4.0.1 switch cran mirror
INWTlab/r-docker pull request #15
Opened 2023-06-16 14:35 UTC by jan-abel-inwt

* added the new script `get_mirror_date.R`  to choose the correct mirror date
* switched from mran to posit cran mirror in the `Dockerfile` using the script

As a result of these modifications, the following mirror URL has been configured:

```
root@f442af7c6b21:~# cat /usr/local/lib/R/etc/Rprofile.site 
options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/2020-06-04'), download.file.method = 'libcurl')
```

2023-06-16 14:46 UTC, jonathan-inwt requested changes

2023-06-16 14:46 UTC, jonathan-inwt commented on r-base/get_mirror_date.R
> +  ifelse(stat == "200", TRUE, FALSE)
```suggestion
  stat <- attr(curlGetHeaders(url), "status")
  stat == 200
```

2023-06-16 14:46 UTC, jonathan-inwt commented on r-base/get_mirror_date.R
> +  paste0("https://packagemanager.posit.co/cran/", format(date, "%Y-%m-%d"))
```suggestion
  sprintf("https://packagemanager.posit.co/cran/%s/src/contrib/PACKAGES", format(date, "%Y-%m-%d"))
```

2023-06-16 14:46 UTC, jonathan-inwt commented on r-model/Dockerfile
> +   && installPackage prophet \
Hier gab es vermutlich einen Grund für das feste Datum.

2023-06-16 14:46 UTC, jonathan-inwt commented on r-base/validate-settings.R
> +      path <- paste0(r, "/src/contrib/PACKAGES")
Bei MRAN mussten wir `src/contrib/packages` nicht angeben, deshalb brauchen wir das hier?

2023-06-16 14:46 UTC, jonathan-inwt commented on r-base/Dockerfile
> +    && echo "options(repos = c(getOption('repos'), INWTRAN = 'https://cran.inwt-statistics.de/2020-06-21'))" >> /usr/local/lib/R/etc/Rprofile.site \
Optimalerweise haben wir hier Snapshots von den selben Daten, von denen wir auch auf Posit zugreifen. Das ist aber vermutlich nicht der Fall?

2023-06-16 14:50 UTC, jan-abel-inwt commented on r-base/validate-settings.R
> +      path <- paste0(r, "/src/contrib/PACKAGES")
Ja, genau

2023-06-19 08:25 UTC, jonathan-inwt commented on r-model/Dockerfile
> +   && installPackage prophet \
Hat sich geklärt

2023-06-19 08:33 UTC, jan-abel-inwt commented on r-model/Dockerfile
> +   && installPackage prophet \
wurde von Andreas vor 2 Jahren geändert.

2023-06-19 08:34 UTC, jan-abel-inwt commented on r-base/Dockerfile
> +    && echo "options(repos = c(getOption('repos'), INWTRAN = 'https://cran.inwt-statistics.de/2020-06-21'))" >> /usr/local/lib/R/etc/Rprofile.site \
Wir gehen weg von den festgesetzten Datum auf das Datum der get_mirror_date funktion

2023-06-19 08:36 UTC, jonathan-inwt approved these changes

2023-06-19 09:16 UTC, merged